spring.application.name=question4-ecommerce-product-api
spring.datasource.url=jdbc:postgresql://localhost:5433/ecommerce_db
spring.datasource.username=postgres
spring.datasource.password=Tracy@120
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect